name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0-rc.3'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Pyright (type check)
        run: uv run pyright

      - name: Pytest
        env:
          PYTHONUNBUFFERED: '1'
        run: uv run pytest -q
